" A simple vimrc settings

set nu              " show line number

set expandtab       " use space instead of tabs
set tabstop=4       " set tab length to 4
set softtabstop=4   " make backspace delete 4 spaces
set shiftwidth=4    " set indent size to 4
set autoindent      "
set smartindent     " auto indent when start a new line

set hlsearch        " hight light search result

set ruler           " enable status bar at the bottom

" remove all trailing white space on each save for all files
autocmd BufWritePre * :%s/\s\+$//e

" back to last modifying postion when opening the file again
autocmd BufReadPost *
    \ if line("'\"")>0&&line("'\"")<=line("$") |
    \   exe "normal g'\"" |
    \ endif
